### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by AliDiaa0** [thegreatrazz/VGAPainter#1]
Hello,
how can I download "VGAPainter" as an installer to Windows and use it?

**Comment by itisrazza** [comment]
I'm not planning to make an installer for this project. Windows 10/11 has a [Microsoft Store](https://www.microsoft.com/store/apps/9NLF1CTQ6Z49) build available.

For anything else, this is a portable program and add it to the Start Menu. Linux and macOS can use Mono.
